services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    build:
      context: rockylinux10
    volumes:
      - $PWD/backup_db_cloudinary.sh:/tmp/backup_db.sh
    networks:
      - net
  db_host:
    image: mysql:lts
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: superstrongpassword
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
networks:
  net:
